const configure = [
  // general
  { label: 'Impressions', value: 'impressions', commonCode: 'impressions' },
  { label: 'Clicks', value: 'clicks', commonCode: 'clicks' },
  { label: 'CPC', value: 'cpc', commonCode: 'cpc', isMoney: true, formatter: '$0,0.00' },
  { label: 'CPM', value: 'cpm', commonCode: 'cpm', isMoney: true, formatter: '$0,0.00' },
  { label: 'CTR', value: 'ctr', commonCode: 'ctr', formatter: '0,0.00%' },
  { label: 'Spend', value: 'spend', commonCode: 'cost', isMoney: true, formatter: '$0,0.00' },
  { label: 'Reach', value: 'reach', commonCode: 'reach',
    operate: (summary, current, { useDefault, defaultSummary }) => {
      if (!useDefault) return Infinity
      if (defaultSummary !== undefined) return defaultSummary.reach
      return summary.getValue('reach')
    }
  },

  // actions
  { label: 'Actions: Mobile App Feature Unlocks', value: 'actions:app_custom_event.fb_mobile_achievement_unlocked' },
  { label: 'Actions: Mobile App Starts', value: 'actions:app_custom_event.fb_mobile_activate_app' },
  { label: 'Actions: Mobile App Payment Details', value: 'actions:app_custom_event.fb_mobile_add_payment_info' },
  { label: 'Actions: Mobile App Adds To Cart', value: 'actions:app_custom_event.fb_mobile_add_to_cart' },
  { label: 'Actions: Mobile App Adds to Wishlist', value: 'actions:app_custom_event.fb_mobile_add_to_wishlist' },
  { label: 'Actions: Mobile App Registrations', value: 'actions:app_custom_event.fb_mobile_complete_registration' },
  { label: 'Actions: Mobile App Content Views', value: 'actions:app_custom_event.fb_mobile_content_view' },
  { label: 'Actions: Mobile App Checkouts', value: 'actions:app_custom_event.fb_mobile_initiated_checkout' },
  { label: 'Actions: Mobile App Achievements', value: 'actions:app_custom_event.fb_mobile_level_achieved' },
  { label: 'Actions: Mobile App Purchases', value: 'actions:app_custom_event.fb_mobile_purchase' },
  { label: 'Actions: Mobile App Ratings', value: 'actions:app_custom_event.fb_mobile_rate' },
  { label: 'Actions: Mobile App Searchs', value: 'actions:app_custom_event.fb_mobile_search' },
  { label: 'Actions: Mobile App Credit Spends', value: 'actions:app_custom_event.fb_mobile_spent_credits' },
  { label: 'Actions: Mobile App Tutorial Completions', value: 'actions:app_custom_event.fb_mobile_tutorial_completion' },
  { label: 'Actions: Other Mobile App Actions', value: 'actions:app_custom_event.other' },
  { label: 'Actions: App Installs', value: 'actions:app_install' },
  { label: 'Actions: App Uses', value: 'actions:app_use' },
  { label: 'Actions: Check-ins', value: 'actions:checkin' },
  { label: 'Actions: Post Comments', value: 'actions:comment' },
  { label: 'Actions: Commerce Adds to Cart', value: 'actions:commerce_event.add_to_cart' },
  { label: 'Actions: Commerce Messages to Buy', value: 'actions:commerce_event.message_to_buy' },
  { label: 'Actions: Commerce Purchases', value: 'actions:commerce_event.purchase' },
  { label: 'Actions: Commerce Product Views', value: 'actions:commerce_event.view_content' },
  { label: 'Actions: Credit Spends', value: 'actions:credit_spent' },
  { label: 'Actions: Post Full Views', value: 'actions:full_view' },
  { label: 'Actions: Game Plays', value: 'actions:games.plays' },
  { label: 'Actions: Leads (Form)', value: 'actions:leadgen.other' },
  { label: 'Actions: Page Likes', value: 'actions:like' },
  { label: 'Actions: Link Clicks', value: 'actions:link_click' },
  { label: 'Actions: Message Blocks', value: 'actions:messenger.block' },
  { label: 'Actions: Message Replys', value: 'actions:messenger.reply' },
  { label: 'Actions: Mobile App Installs', value: 'actions:mobile_app_install' },
  { label: 'Actions: Newly Purchased Mobile Devices', value: 'actions:new_mobile' },

  { label: 'Actions: Custom Conversions defined by the advertiser', value: 'actions:offsite_conversion.<custom_conv_id>', match: (value) => (value.match(/actions:offsite_conversion\.custom\.[0-9]/) || value === 'actions:offsite_conversion.<custom_conv_id>'),
    translate: function (translateFunction) {
      const convId = this.code.splite('.').pop()
      const suffix = convId.match(/[0-9]/) ? ` - ${convId}` : ''
      if (typeof translateFunction === 'function') return `${this.label}${suffix}`
      return `${translateFunction(this.label)}${suffix}`
    }
  },
  { label: 'Actions: Adds to Cart', value: 'actions:offsite_conversion.add_to_cart' },
  { label: 'Actions: Checkouts', value: 'actions:offsite_conversion.checkout' },
  { label: 'Actions: Adds Payment Info', value: 'actions:offsite_conversion.fb_pixel_add_payment_info' },
  { label: 'Actions: Adds To Cart', value: 'actions:offsite_conversion.fb_pixel_add_to_cart' },
  { label: 'Actions: Fb Pixel - Adds To Wishlist', value: 'actions:offsite_conversion.fb_pixel_add_to_wishlist' },
  { label: 'Actions: Fb Pixel - Completes Registration', value: 'actions:offsite_conversion.fb_pixel_complete_registration' },
  { label: 'Actions: Fb Pixel - Custom pixel events defined by the advertiser', value: 'actions:offsite_conversion.fb_pixel_custom' },
  { label: 'Actions: Fb Pixel - Initiates Checkout', value: 'actions:offsite_conversion.fb_pixel_initiate_checkout' },
  { label: 'Actions: Fb Pixel - Leads', value: 'actions:offsite_conversion.fb_pixel_lead' },
  { label: 'Actions: Fb Pixel - Purchases', value: 'actions:offsite_conversion.fb_pixel_purchase' },
  { label: 'Actions: Fb Pixel - Searchs', value: 'actions:offsite_conversion.fb_pixel_search' },
  { label: 'Actions: Fb Pixel - Views Content', value: 'actions:offsite_conversion.fb_pixel_view_content' },
  { label: 'Actions: Key Page Views', value: 'actions:offsite_conversion.key_page_view' },
  { label: 'Actions: Offsite Conversion: Leads', value: 'actions:offsite_conversion.lead' },
  { label: 'Actions: Other Website Conversions', value: 'actions:offsite_conversion.other' },
  { label: 'Actions: Registrations', value: 'actions:offsite_conversion.registration' },
  { label: 'Actions: On-Facebook Workflow Completions', value: 'actions:onsite_conversion.flow_complete' },
  { label: 'Actions: Blocked Messaging Conversations', value: 'actions:onsite_conversion.messaging_block' },
  { label: 'Actions: New Messaging Conversations', value: 'actions:onsite_conversion.messaging_first_reply' },
  { label: 'Actions: Messaging Replys', value: 'actions:onsite_conversion.messaging_reply' },
  { label: 'Actions: On-Facebook Purchases', value: 'actions:onsite_conversion.purchase' },
  { label: 'Actions: Outbound Clicks', value: 'actions:outbound_click' },
  { label: 'Actions: Page Photo Views', value: 'actions:photo_view' },
  { label: 'Actions: Post Shares', value: 'actions:post' },
  { label: 'Actions: Post Reactions', value: 'actions:post_reaction' },
  { label: 'Actions: Offer Claims', value: 'actions:receive_offer' },
  { label: 'Actions: Event Responses', value: 'actions:rsvp' },
  { label: 'Actions: 3-Second Video Views', value: 'actions:video_view' },
  { label: 'Actions: Landing Page View', value: 'actions:landing_page_view' },

  { label: 'Actions: App Engagement (Grouped)', value: 'actions:app_engagement' },
  { label: 'Actions: App Story (Grouped)', value: 'actions:app_story' },
  { label: 'Actions: Commerce Event (Grouped)', value: 'actions:commerce_event' },
  { label: 'Actions: Page Engagement (Grouped)', value: 'actions:page_engagement' },
  { label: 'Actions: Page Story (Grouped)', value: 'actions:page_story' },
  { label: 'Actions: Post Engagement (Grouped)', value: 'actions:post_engagement' },
  { label: 'Actions: Post Story (Grouped)', value: 'actions:post_story' },
  { label: 'Actions: Offsite Conversion (Grouped)', value: 'actions:offsite_conversion' },
  { label: 'Actions: Onsite Conversion (Grouped)', value: 'actions:onsite_conversion' },
  { label: 'Actions: App Custom Event (Grouped)', value: 'actions:app_custom_event' },
  { label: 'Actions: Mobile App Retention (Grouped)', value: 'actions:mobile_app_retention' },
  { label: 'Actions: Mobile App Roas (Grouped)', value: 'actions:mobile_app_roas' },
  { label: 'Actions: Offsite Engagement (Grouped)', value: 'actions:offsite_engagement' },
  { label: 'Actions: Offline Conversion (Grouped)', value: 'actions:offline_conversion' },
  { label: 'Actions: Store Visit With Dwell (Grouped)', value: 'actions:store_visit_with_dwell' },
  { label: 'Actions: Add To Cart (Grouped)', value: 'actions:add_to_cart' },
  { label: 'Actions: Complete Registration (Grouped)', value: 'actions:complete_registration' },
  { label: 'Actions: Purchase (Grouped)', value: 'actions:purchase' },
  { label: 'Actions: Search (Grouped)', value: 'actions:search' },
  { label: 'Actions: View Content (Grouped)', value: 'actions:view_content' },

  // cost per action
  { label: 'Cost Per Action Type: Mobile App Feature Unlocks', value: 'cost_per_action_type:app_custom_event.fb_mobile_achievement_unlocked', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_achievement_unlocked')) },
  { label: 'Cost Per Action Type: Mobile App Starts', value: 'cost_per_action_type:app_custom_event.fb_mobile_activate_app', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_activate_app')) },
  { label: 'Cost Per Action Type: Mobile App Payment Details', value: 'cost_per_action_type:app_custom_event.fb_mobile_add_payment_info', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_add_payment_info')) },
  { label: 'Cost Per Action Type: Mobile App Adds To Cart', value: 'cost_per_action_type:app_custom_event.fb_mobile_add_to_cart', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_add_to_cart')) },
  { label: 'Cost Per Action Type: Mobile App Adds to Wishlist', value: 'cost_per_action_type:app_custom_event.fb_mobile_add_to_wishlist', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_add_to_wishlist')) },
  { label: 'Cost Per Action Type: Mobile App Registrations', value: 'cost_per_action_type:app_custom_event.fb_mobile_complete_registration', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_complete_registration')) },
  { label: 'Cost Per Action Type: Mobile App Content Views', value: 'cost_per_action_type:app_custom_event.fb_mobile_content_view', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_content_view')) },
  { label: 'Cost Per Action Type: Mobile App Checkouts', value: 'cost_per_action_type:app_custom_event.fb_mobile_initiated_checkout', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_initiated_checkout')) },
  { label: 'Cost Per Action Type: Mobile App Achievements', value: 'cost_per_action_type:app_custom_event.fb_mobile_level_achieved', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_level_achieved')) },
  { label: 'Cost Per Action Type: Mobile App Purchases', value: 'cost_per_action_type:app_custom_event.fb_mobile_purchase', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_purchase')) },
  { label: 'Cost Per Action Type: Mobile App Ratings', value: 'cost_per_action_type:app_custom_event.fb_mobile_rate', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_rate')) },
  { label: 'Cost Per Action Type: Mobile App Searchs', value: 'cost_per_action_type:app_custom_event.fb_mobile_search', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_search')) },
  { label: 'Cost Per Action Type: Mobile App Credit Spends', value: 'cost_per_action_type:app_custom_event.fb_mobile_spent_credits', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_spent_credits')) },
  { label: 'Cost Per Action Type: Mobile App Tutorial Completions', value: 'cost_per_action_type:app_custom_event.fb_mobile_tutorial_completion', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.fb_mobile_tutorial_completion')) },
  { label: 'Cost Per Action Type: Other Mobile App Actions', value: 'cost_per_action_type:app_custom_event.other', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event.other')) },
  { label: 'Cost Per Action Type: App Installs', value: 'cost_per_action_type:app_install', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_install')) },
  { label: 'Cost Per Action Type: App Uses', value: 'cost_per_action_type:app_use', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_use')) },
  { label: 'Cost Per Action Type: Check-ins', value: 'cost_per_action_type:checkin', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:checkin')) },
  { label: 'Cost Per Action Type: Post Comments', value: 'cost_per_action_type:comment', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:comment')) },
  { label: 'Cost Per Action Type: Commerce Adds to Cart', value: 'cost_per_action_type:commerce_event.add_to_cart', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:commerce_event.add_to_cart')) },
  { label: 'Cost Per Action Type: Commerce Messages to Buy', value: 'cost_per_action_type:commerce_event.message_to_buy', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:commerce_event.message_to_buy')) },
  { label: 'Cost Per Action Type: Commerce Purchases', value: 'cost_per_action_type:commerce_event.purchase', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:commerce_event.purchase')) },
  { label: 'Cost Per Action Type: Commerce Product Views', value: 'cost_per_action_type:commerce_event.view_content', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:commerce_event.view_content')) },
  { label: 'Cost Per Action Type: Credit Spends', value: 'cost_per_action_type:credit_spent', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:credit_spent')) },
  { label: 'Cost Per Action Type: Post Full Views', value: 'cost_per_action_type:full_view', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:full_view')) },
  { label: 'Cost Per Action Type: Game Plays', value: 'cost_per_action_type:games.plays', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:games.plays')) },
  { label: 'Cost Per Action Type: Leads (Form)', value: 'cost_per_action_type:leadgen.other', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:leadgen.other')) },
  { label: 'Cost Per Action Type: Page Likes', value: 'cost_per_action_type:like', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:like')) },
  { label: 'Cost Per Action Type: Link Clicks', value: 'cost_per_action_type:link_click', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:link_click')) },
  { label: 'Cost Per Action Type: Message Blocks', value: 'cost_per_action_type:messenger.block', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:messenger.block')) },
  { label: 'Cost Per Action Type: Message Replys', value: 'cost_per_action_type:messenger.reply', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:messenger.reply')) },
  { label: 'Cost Per Action Type: Mobile App Installs', value: 'cost_per_action_type:mobile_app_install', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:mobile_app_install')) },
  { label: 'Cost Per Action Type: Newly Purchased Mobile Devices', value: 'cost_per_action_type:new_mobile', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:new_mobile')) },

  { label: 'Cost Per Action Type: Custom Conversions defined by the advertiser', value: 'cost_per_action_type:offsite_conversion.<custom_conv_id>', match: (value) => (value.match(/cost_per_action_type:offsite_conversion\.custom\.[0-9]/) || value === 'cost_per_action_type:offsite_conversion.<custom_conv_id>'), isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.<custom_conv_id>')),
    translate: function (translateFunction) {
      const convId = this.code.splite('.').pop()
      const suffix = convId.match(/[0-9]/) ? ` - ${convId}` : ''
      if (typeof translateFunction === 'function') return `${this.label}${suffix}`
      return `${translateFunction(this.label)}${suffix}`
    }
  },
  { label: 'Cost Per Action Type: Adds to Cart', value: 'cost_per_action_type:offsite_conversion.add_to_cart', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.add_to_cart')) },
  { label: 'Cost Per Action Type: Checkouts', value: 'cost_per_action_type:offsite_conversion.checkout', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.checkout')) },
  { label: 'Cost Per Action Type: Adds Payment Info', value: 'cost_per_action_type:offsite_conversion.fb_pixel_add_payment_info', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_add_payment_info')) },
  { label: 'Cost Per Action Type: Adds To Cart', value: 'cost_per_action_type:offsite_conversion.fb_pixel_add_to_cart', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_add_to_cart')) },
  { label: 'Cost Per Action Type: Fb Pixel - Adds To Wishlist', value: 'cost_per_action_type:offsite_conversion.fb_pixel_add_to_wishlist', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_add_to_wishlist')) },
  { label: 'Cost Per Action Type: Fb Pixel - Completes Registration', value: 'cost_per_action_type:offsite_conversion.fb_pixel_complete_registration', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_complete_registration')) },
  { label: 'Cost Per Action Type: Fb Pixel - Custom pixel events defined by the advertiser', value: 'cost_per_action_type:offsite_conversion.fb_pixel_custom', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_custom')) },
  { label: 'Cost Per Action Type: Fb Pixel - Initiates Checkout', value: 'cost_per_action_type:offsite_conversion.fb_pixel_initiate_checkout', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_initiate_checkout')) },
  { label: 'Cost Per Action Type: Fb Pixel - Leads', value: 'cost_per_action_type:offsite_conversion.fb_pixel_lead', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_lead')) },
  { label: 'Cost Per Action Type: Fb Pixel - Purchases', value: 'cost_per_action_type:offsite_conversion.fb_pixel_purchase', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_purchase')) },
  { label: 'Cost Per Action Type: Fb Pixel - Searchs', value: 'cost_per_action_type:offsite_conversion.fb_pixel_search', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_search')) },
  { label: 'Cost Per Action Type: Fb Pixel - Views Content', value: 'cost_per_action_type:offsite_conversion.fb_pixel_view_content', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.fb_pixel_view_content')) },
  { label: 'Cost Per Action Type: Key Page Views', value: 'cost_per_action_type:offsite_conversion.key_page_view', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.key_page_view')) },
  { label: 'Cost Per Action Type: Offsite Conversion: Leads', value: 'cost_per_action_type:offsite_conversion.lead', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.lead')) },
  { label: 'Cost Per Action Type: Other Website Conversions', value: 'cost_per_action_type:offsite_conversion.other', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.other')) },
  { label: 'Cost Per Action Type: Registrations', value: 'cost_per_action_type:offsite_conversion.registration', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion.registration')) },
  { label: 'Cost Per Action Type: On-Facebook Workflow Completions', value: 'cost_per_action_type:onsite_conversion.flow_complete', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:onsite_conversion.flow_complete')) },
  { label: 'Cost Per Action Type: Blocked Messaging Conversations', value: 'cost_per_action_type:onsite_conversion.messaging_block', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:onsite_conversion.messaging_block')) },
  { label: 'Cost Per Action Type: New Messaging Conversations', value: 'cost_per_action_type:onsite_conversion.messaging_first_reply', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:onsite_conversion.messaging_first_reply')) },
  { label: 'Cost Per Action Type: Messaging Replys', value: 'cost_per_action_type:onsite_conversion.messaging_reply', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:onsite_conversion.messaging_reply')) },
  { label: 'Cost Per Action Type: On-Facebook Purchases', value: 'cost_per_action_type:onsite_conversion.purchase', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:onsite_conversion.purchase')) },
  { label: 'Cost Per Action Type: Outbound Clicks', value: 'cost_per_action_type:outbound_click', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:outbound_click')) },
  { label: 'Cost Per Action Type: Page Photo Views', value: 'cost_per_action_type:photo_view', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:photo_view')) },
  { label: 'Cost Per Action Type: Post Shares', value: 'cost_per_action_type:post', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:post')) },
  { label: 'Cost Per Action Type: Post Reactions', value: 'cost_per_action_type:post_reaction', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:post_reaction')) },
  { label: 'Cost Per Action Type: Offer Claims', value: 'cost_per_action_type:receive_offer', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:receive_offer')) },
  { label: 'Cost Per Action Type: Event Responses', value: 'cost_per_action_type:rsvp', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:rsvp')) },
  { label: 'Cost Per Action Type: 3-Second Video Views', value: 'cost_per_action_type:video_view', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:video_view')) },
  { label: 'Cost Per Action Type: Landing Page View', value: 'cost_per_action_type:landing_page_view', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:landing_page_view')) },

  { label: 'Cost Per Action Type: App Engagement (Grouped)', value: 'cost_per_action_type:app_engagement', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_engagement')) },
  { label: 'Cost Per Action Type: App Story (Grouped)', value: 'cost_per_action_type:app_story', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_story')) },
  { label: 'Cost Per Action Type: Commerce Event (Grouped)', value: 'cost_per_action_type:commerce_event', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:commerce_event')) },
  { label: 'Cost Per Action Type: Page Engagement (Grouped)', value: 'cost_per_action_type:page_engagement', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:page_engagement')) },
  { label: 'Cost Per Action Type: Page Story (Grouped)', value: 'cost_per_action_type:page_story', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:page_story')) },
  { label: 'Cost Per Action Type: Post Engagement (Grouped)', value: 'cost_per_action_type:post_engagement', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:post_engagement')) },
  { label: 'Cost Per Action Type: Post Story (Grouped)', value: 'cost_per_action_type:post_story', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:post_story')) },
  { label: 'Cost Per Action Type: Offsite Conversion (Grouped)', value: 'cost_per_action_type:offsite_conversion', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_conversion')) },
  { label: 'Cost Per Action Type: Onsite Conversion (Grouped)', value: 'cost_per_action_type:onsite_conversion', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:onsite_conversion')) },
  { label: 'Cost Per Action Type: App Custom Event (Grouped)', value: 'cost_per_action_type:app_custom_event', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:app_custom_event')) },
  { label: 'Cost Per Action Type: Mobile App Retention (Grouped)', value: 'cost_per_action_type:mobile_app_retention', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:mobile_app_retention')) },
  { label: 'Cost Per Action Type: Mobile App Roas (Grouped)', value: 'cost_per_action_type:mobile_app_roas', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:mobile_app_roas')) },
  { label: 'Cost Per Action Type: Offsite Engagement (Grouped)', value: 'cost_per_action_type:offsite_engagement', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offsite_engagement')) },
  { label: 'Cost Per Action Type: Offline Conversion (Grouped)', value: 'cost_per_action_type:offline_conversion', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:offline_conversion')) },
  { label: 'Cost Per Action Type: Store Visit With Dwell (Grouped)', value: 'cost_per_action_type:store_visit_with_dwell', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:store_visit_with_dwell')) },
  { label: 'Cost Per Action Type: Add To Cart (Grouped)', value: 'cost_per_action_type:add_to_cart', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:add_to_cart')) },
  { label: 'Cost Per Action Type: Complete Registration (Grouped)', value: 'cost_per_action_type:complete_registration', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:complete_registration')) },
  { label: 'Cost Per Action Type: Purchase (Grouped)', value: 'cost_per_action_type:purchase', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:purchase')) },
  { label: 'Cost Per Action Type: Search (Grouped)', value: 'cost_per_action_type:search', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:search')) },
  { label: 'Cost Per Action Type: View Content (Grouped)', value: 'cost_per_action_type:view_content', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('actions:view_content')) },

  // video action
  { label: 'Video Actions: Video 10 Sec Watched Actions', value: 'video_actions:video_10_sec_watched_actions' },
  { label: 'Video Actions: Video 30 Sec Watched Actions', value: 'video_actions:video_30_sec_watched_actions' },
  { label: 'Video Actions: Video Avg Percent Watched Actions', value: 'video_actions:video_avg_percent_watched_actions' },
  { label: 'Video Actions: Video Avg Time Watched Actions', value: 'video_actions:video_avg_time_watched_actions' },
  { label: 'Video Actions: Video Complete Watched Actions', value: 'video_actions:video_complete_watched_actions' },
  { label: 'Video Actions: Video P100 Watched Actions', value: 'video_actions:video_p100_watched_actions' },
  { label: 'Video Actions: Video P25 Watched Actions', value: 'video_actions:video_p25_watched_actions' },
  { label: 'Video Actions: Video P75 Watched Actions', value: 'video_actions:video_p75_watched_actions' },
  { label: 'Video Actions: Video P95 Watched Actions', value: 'video_actions:video_p95_watched_actions' },

  // cost per video action
  { label: 'Cost Per 10 Sec Video View', value: 'cost_per_10_sec_video_view', isMoney: true, formatter: '$0,0.00', operate: (summary, current) => (summary.getValue('spend') / summary.getValue('video_actions:video_10_sec_watched_actions')) }
]

export default configure
